name: training_One

on:
  push:
    branches: [main]

jobs:
  ci-training:
    name: CI training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Check-Up Node Modules
        run: npm audit --audit-level=high
      - name: Init static version of Node Modules from package-lock.json
        run: npm ci
      - name: ESLint
        run: npm run lint:check
      - name: TS Compilation
        run: npm run compile
      - name:
        run: npm run build:firefox
