name: training_One

on:
  push:
    branches: [main]

jobs:
  ci-training:
    name: CI training
    runs-on: ubuntu-latest
    steps:
      - name: Init static version of Node Modules from package-lock.json
        run: npm install
      - name: Check-Up Node Modules
        run: npm audit --audit-level=critical
      - name: ESLint
        run: npm run lint:check
      - name: TS Compilation
        run: npm run compile
      - name:
        run: npm run build:firefox
